### PR TITLE
Add support for arrow-style features

### PR DESCRIPTION
**Pull request by althonos**
Hi !

I've been using this library extensively to render gene features, but one thing that bothered us was the lack of support for arrows to show gene direction. This PR addresses this issue by adding the `arrow` feature type to show the direction of a feature:

arrow-example

To set the feature direction, simply set a `direction` attribute at the datum level. If not specified, the default direction is `right`.

Hopefully I did everything right, I used the `rect` feature type as an example!

### CODE REVIEW

**Review by Lisanna — APPROVED** [review]

**Review by Lisanna — APPROVED** [review]
Ok, approved

**Comment by Lisanna** [comment]
I'll extensively test and then publish another version. Thanks!

**Comment by althonos** [comment]
Thanks! Normally, I've handled the case where the arrow is too small to be drawn, in which case it is replaced by a single rectangle, but there may be some issues I didn't think of.

**Comment by Lisanna** [comment]
New version published, sorry for the delay.
I noticed that, in case of multiple overlapping arrows, they are simply superimposed (see figure). I know this is not probably your use case (as genes tend not overlap), but is this the expected behavior?
Screenshot at 2020-10-30 12-20-02

**Comment by althonos** [comment]
I actually do have some overlapping genes, since I look at bacterial genomes and use a gene finder so it's not uncommon to have genes overlapping at their boundaries, which is why I didn't implement the multiple track like `rect` to avoid cluttering the view for just a few overlapping bases:
screen

**Comment by Lisanna** [comment]
So, would you prefer them to behave like multipleRects like this?
Screenshot at 2020-10-30 13-30-41

**Comment by althonos** [comment]
I think I only need the overlapping version, but I totally agree it would be nice to have the non-overlapping option at disposal (tbh, I didn't really trying delving into the `drawMultipleRect` code :sweat_smile: 

Also, one thing that would be nice for ORF rendering would be an option to split the features by direction (independently of the overlap) to have a track for the coding strand and a track for the reverse strand. This can probably be done using subfeatures and manually splitting the features but it would probably be nicer if it was builtin!

**Pull request merged**
